version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospital
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata:
